[package]
name = "yt-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
futures = "0.3.31"
rspotify = { version = "0.14.0", features = ["cli", "env-file"]}
rustypipe = "0.11.4"
tokio = {version= "1.45.1", features=["full"]}
